LOG_PATH = '/opt/logs'
AWS_ACCESS_KEY = 'AKIAPYN3LFSCIELSML6A'
AWS_ACCESS_SECRET = '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'
AWS_REGION = 'cn-north-1'
DYNAMODB_ENDPOINT='https://dynamodb.cn-north-1.amazonaws.com.cn'